### ISSUE TITLE
Crear informe de aportaciones realizadas en tercer entregable

### ISSUE THREAD

**Issue by labra** [Arquisoft/dechat_es6a2#26]
Cada miembro del equipo debe responder a este issue con un breve informe de las aportaciones más importantes que ha realizado al proyecto hasta el tercer entregable.

**Comment by othub** [comment]
## Primer Entregable en _ES6A_
* trabajar sobre documentación 
* buscar ideas y proyectos y hacer tutoriales de solid.

## Segundo Entregable en _ES6A_
* trabajar sobre funcionalidad y ui junto a **Jorge A. Fidalgo** para conseguir la version 0.1 .
* configurar travis y hacer test demo para el build.

## Tercer Entregable 
* configurar travis y codecov
* hacer tests unitarios con mocha y nyc istanbul .
* hacer tests de *BDD* con cucumber-selenium.
* trabajar sobre documentación.

**Comment by jorgealvarezfidalgo** [comment]
## Primer Entregable en _ES6A_
* Documentación: _Architectural Constraints_.
* Estudiar el funcionamiento del proyecto Solid-Chess como posible punto de referencia.

## Segundo Entregable en _ES6A_
* Creación de la funcionalidad básica de envío y recibo de mensajes dentro del marco de un chat persistente y accesible mediante invitación.
* Creación de interfaz básica que permite iniciar sesión, crear, unirse y abrir un chat; desde el cual se envían y reciben los mensajes.

## Tercer Entregable 
* Remodelación completa de la interfaz, aportando un diseño habitual para esta funcionalidad que comprende mayores posibilidades así como una interacción más simple.
* Reestructuración total de la lógica en módulos y clases de cara a conseguir una mejor y más manejable arquitectura. 
* Mejora de la funcionalidad previa: eliminar todo acceso público a los datos, reestructurando el sistema de invitaciones y el almacenamiento de chats.
* Nueva funcionalidad: 
1. Chats grupales.
2. Añadir contactos de forma dinámica para la creación de chats y grupos.
3. Uso de smileys y gifs.
4. Notificaciones de nuevos mensajes en chats abiertos y nuevas invitaciones.
5. Detalles de contactos.
* Documentación: secciones III, V y VII
* Despliegue de la app en Github Pages

**Comment by jorgealvarezfidalgo** [comment]
## Cuarto Entregable 
* Sistema de encriptación original para el envío y almacenamiento de información.
* Comentado de la totalidad del código. 
* Mejora de la interfaz: 
1. Bloqueo de la entrada de mensajes si no hay chat abierto.
2. Uso de paneles mejorado para no modificar la estructura durante operaciones dinámicas.
3. Estilo de página general más refinado.
4. Eliminación de la repetición de eventos de botón (al activar mientras se ejecuta la operación)
5. Ayuda incluida.

**Comment by othub** [comment]
## Cuarto Entregable

- Añadir soporte para mensajes de tipo imagen, video, audio, y texto.
- Añadir menu de emojis 
- Incluir Gatling y añadir tests de performance.
